name: Core Back-end Tests

on:
  push: []
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  core_back-end_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.0.2, 8.1 ]
    steps:
    - uses: shivammathur/setup-php@2.28.0
      with:
        php-version: ${{ matrix.php-version }}
      env:
        COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: composer install --quiet --no-ansi --no-interaction --no-progress
    - name: Run tests
      run: composer run test:offline:fast
